server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://13.209.158.154:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: transaction-feed
          __path__: /app/logs/app.log